# Generated by Django 4.1.3 on 2022-11-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Residencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroResidencia", models.CharField(max_length=200)),
                ("edificio", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Correspondencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinatario", models.CharField(max_length=200)),
                ("fecha", models.DateTimeField()),
                (
                    "residencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conserjeria.residencia",
                    ),
                ),
            ],
        ),
    ]
