# Generated by Django 4.1.3 on 2022-11-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conserjeria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondencia",
            name="entregado",
            field=models.BooleanField(default=False),
        ),
    ]
